mysqldata:
  build: ./docker/mysql
  entrypoint: /bin/bash
mysql:
  build: ./docker/mysql
  ports:
   - "3306"
  env_file: ./docker/mysql/.env
  volumes_from:
    - mysqldata
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=drupal
mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1081:1080"
      - "1025:1025"
web:
  build: ./docker/web
  ports:
   - "80"
  env_file: ./docker/web/.env
  volumes:
   - .:/var/www/mirror
   - ~/.ssh:/root/.ssh
   - ./volumes/xdebug_profiler:/root/xdebug_profiler
  links:
   - mysql:mysql
   - mailcatcher
